<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Empowerment;
use App\Models\User;
use App\Models\Ward;
use Carbon\Carbon;

class EmpowermentSeeder extends Seeder
{
    public function run(): void
    {
        $coordinators = User::whereHas('role', fn($q) => $q->whereIn('name', ['WDC', 'CDFC', 'Officer']))->get();
        $approvers = User::whereHas('role', fn($q) => $q->whereIn('name', ['CDFC', 'Admin']))->get();
        $wards = Ward::all();

        $programs = [
            [
                'program_code' => 'EMP-2024-001',
                'title' => 'Digital Literacy Training Program',
                'description' => 'Comprehensive digital literacy training for community members to improve their computer and internet skills.',
                'program_type' => 'Digital_Literacy',
                'target_group' => 'Youth',
                'status' => 'Active',
                'ward_id' => $wards->random()->id,
                'venue' => 'Kanyama Community Center',
                'target_participants' => 30,
                'registered_participants' => 25,
                'completed_participants' => 20,
                'objectives' => 'To provide basic computer skills, internet navigation, and digital communication skills to youth in the community.',
                'curriculum' => 'Week 1: Computer basics, Week 2: Internet navigation, Week 3: Email and communication, Week 4: Digital security',
                'duration_hours' => 40,
                'duration_days' => 10,
                'prerequisites' => 'Basic literacy skills, age 18-35',
                'required_materials' => 'Notebooks, pens, printed materials',
                'equipment_needed' => '15 computers, projector, internet connection',
                'facilitators' => 'John Mwanza (IT Specialist), Mary Tembo (Digital Trainer)',
                'start_date' => Carbon::now()->subDays(20),
                'end_date' => Carbon::now()->addDays(10),
                'session_time' => '09:00:00',
                'registration_deadline' => Carbon::now()->subDays(25),
                'frequency' => 'Daily',
                'total_budget' => 15000.00,
                'allocated_budget' => 15000.00,
                'spent_amount' => 8500.00,
                'cost_per_participant' => 500.00,
                'funding_source' => 'CDF',
                'expected_outcomes' => 'Participants will be able to use computers confidently, navigate the internet, and communicate digitally.',
                'success_indicators' => 'Certificate completion rate above 80%, post-training assessment scores above 75%',
                'completion_rate_target' => 80.00,
                'satisfaction_target' => 85.00,
                'coordinator_id' => $coordinators->random()->id,
                'approved_by_id' => $approvers->random()->id,
                'implementation_notes' => 'Program running smoothly with high engagement from participants',
                'evaluation_notes' => 'Participants showing good progress in practical sessions',
            ],
            [
                'program_code' => 'EMP-2024-002',
                'title' => 'Women Business Development Workshop',
                'description' => 'Intensive business development workshop for women entrepreneurs in the community.',
                'program_type' => 'Business_Development',
                'target_group' => 'Women',
                'status' => 'Completed',
                'ward_id' => $wards->random()->id,
                'venue' => 'Matero Women Center',
                'target_participants' => 25,
                'registered_participants' => 25,
                'completed_participants' => 22,
                'objectives' => 'To equip women with business planning, financial management, and marketing skills.',
                'curriculum' => 'Business planning, Financial management, Marketing strategies, Legal requirements for small business',
                'duration_hours' => 24,
                'duration_days' => 6,
                'prerequisites' => 'Existing small business or business idea, basic literacy',
                'required_materials' => 'Business planning templates, calculators, flipchart papers',
                'equipment_needed' => 'Training hall, projector, sound system',
                'facilitators' => 'Grace Mulenga (Business Consultant), Peter Chanda (Financial Advisor)',
                'start_date' => Carbon::now()->subDays(45),
                'end_date' => Carbon::now()->subDays(35),
                'session_time' => '14:00:00',
                'registration_deadline' => Carbon::now()->subDays(50),
                'frequency' => 'Bi-Weekly',
                'total_budget' => 8000.00,
                'allocated_budget' => 8000.00,
                'spent_amount' => 7800.00,
                'cost_per_participant' => 320.00,
                'funding_source' => 'CDF',
                'expected_outcomes' => 'Women will develop comprehensive business plans and improve their business management skills.',
                'success_indicators' => 'Business plan completion rate, increased monthly income by 30%',
                'completion_rate_target' => 85.00,
                'satisfaction_target' => 90.00,
                'coordinator_id' => $coordinators->random()->id,
                'approved_by_id' => $approvers->random()->id,
                'implementation_notes' => 'Successfully completed with excellent feedback from participants',
                'evaluation_notes' => 'High satisfaction rate, many participants have started implementing their business plans',
            ],
            [
                'program_code' => 'EMP-2024-003',
                'title' => 'Youth Leadership Development Program',
                'description' => 'Leadership training program designed to develop leadership skills among young people in the community.',
                'program_type' => 'Leadership_Development',
                'target_group' => 'Youth',
                'status' => 'Ongoing',
                'ward_id' => $wards->random()->id,
                'venue' => 'Munali Youth Center',
                'target_participants' => 40,
                'registered_participants' => 38,
                'completed_participants' => 0,
                'objectives' => 'To develop leadership skills, communication abilities, and community engagement among youth.',
                'curriculum' => 'Leadership principles, Communication skills, Project management, Community service planning',
                'duration_hours' => 32,
                'duration_days' => 8,
                'prerequisites' => 'Age 18-30, interest in community leadership',
                'required_materials' => 'Leadership handbooks, project planning templates',
                'equipment_needed' => 'Training facility, audio-visual equipment',
                'facilitators' => 'Dr. Susan Banda (Leadership Expert), James Phiri (Youth Coordinator)',
                'start_date' => Carbon::now()->subDays(5),
                'end_date' => Carbon::now()->addDays(15),
                'session_time' => '10:00:00',
                'registration_deadline' => Carbon::now()->subDays(10),
                'frequency' => 'Weekly',
                'total_budget' => 12000.00,
                'allocated_budget' => 12000.00,
                'spent_amount' => 3000.00,
                'cost_per_participant' => 300.00,
                'funding_source' => 'CDF',
                'expected_outcomes' => 'Youth will develop strong leadership skills and engage in community development activities.',
                'success_indicators' => 'Leadership assessment scores, community project proposals developed',
                'completion_rate_target' => 85.00,
                'satisfaction_target' => 88.00,
                'coordinator_id' => $coordinators->random()->id,
                'approved_by_id' => $approvers->random()->id,
                'implementation_notes' => 'Program started well with enthusiastic participation',
                'evaluation_notes' => 'Early sessions showing good engagement and learning',
            ],
            [
                'program_code' => 'EMP-2024-004',
                'title' => 'Agricultural Skills Training',
                'description' => 'Modern farming techniques and sustainable agriculture training for community farmers.',
                'program_type' => 'Agricultural_Training',
                'target_group' => 'Farmers',
                'status' => 'Approved',
                'ward_id' => $wards->random()->id,
                'venue' => 'Chongwe Agricultural Training Center',
                'target_participants' => 50,
                'registered_participants' => 45,
                'completed_participants' => 0,
                'objectives' => 'To improve agricultural productivity through modern farming techniques and sustainable practices.',
                'curriculum' => 'Soil management, Crop rotation, Pest control, Post-harvest handling, Market linkages',
                'duration_hours' => 48,
                'duration_days' => 12,
                'prerequisites' => 'Active in farming, access to farmland',
                'required_materials' => 'Farming manuals, seed samples, soil testing kits',
                'equipment_needed' => 'Demonstration plots, farming tools, testing equipment',
                'facilitators' => 'Agricultural Extension Officers, Soil Specialists',
                'start_date' => Carbon::now()->addDays(10),
                'end_date' => Carbon::now()->addDays(25),
                'session_time' => '08:00:00',
                'registration_deadline' => Carbon::now()->addDays(5),
                'frequency' => 'Daily',
                'total_budget' => 18000.00,
                'allocated_budget' => 18000.00,
                'spent_amount' => 0.00,
                'cost_per_participant' => 360.00,
                'funding_source' => 'CDF',
                'expected_outcomes' => 'Increased crop yields and improved farming practices among participants.',
                'success_indicators' => 'Adoption of new techniques, increased harvest yields by 25%',
                'completion_rate_target' => 80.00,
                'satisfaction_target' => 85.00,
                'coordinator_id' => $coordinators->random()->id,
                'approved_by_id' => $approvers->random()->id,
                'implementation_notes' => 'Awaiting final preparations before program start',
                'evaluation_notes' => 'High registration interest from farming community',
            ],
            [
                'program_code' => 'EMP-2024-005',
                'title' => 'Financial Literacy Workshop',
                'description' => 'Basic financial literacy and savings training for community members.',
                'program_type' => 'Financial_Literacy',
                'target_group' => 'General',
                'status' => 'Planning',
                'ward_id' => $wards->random()->id,
                'venue' => 'Kabwata Community Hall',
                'target_participants' => 35,
                'registered_participants' => 0,
                'completed_participants' => 0,
                'objectives' => 'To improve financial management skills and promote savings culture in the community.',
                'curriculum' => 'Personal budgeting, Savings strategies, Understanding credit, Investment basics',
                'duration_hours' => 16,
                'duration_days' => 4,
                'prerequisites' => 'Basic literacy, interest in financial improvement',
                'required_materials' => 'Financial planning worksheets, calculators',
                'equipment_needed' => 'Training venue, flipchart stands, markers',
                'facilitators' => 'Bank Representatives, Financial Advisors',
                'start_date' => Carbon::now()->addDays(30),
                'end_date' => Carbon::now()->addDays(35),
                'session_time' => '15:00:00',
                'registration_deadline' => Carbon::now()->addDays(25),
                'frequency' => 'Daily',
                'total_budget' => 6000.00,
                'allocated_budget' => 0.00,
                'spent_amount' => 0.00,
                'cost_per_participant' => 171.00,
                'funding_source' => 'CDF',
                'expected_outcomes' => 'Improved personal financial management and increased savings rates.',
                'success_indicators' => 'Creation of personal budgets, opening of savings accounts',
                'completion_rate_target' => 75.00,
                'satisfaction_target' => 80.00,
                'coordinator_id' => $coordinators->random()->id,
                'approved_by_id' => null,
                'implementation_notes' => 'Program in planning phase, venue booking in progress',
                'evaluation_notes' => 'Community needs assessment completed',
            ],
        ];

        foreach ($programs as $program) {
            Empowerment::firstOrCreate(
                ['program_code' => $program['program_code']],
                $program
            );
        }
    }
}
